Add #include <limits.h> from sepolgen-ifgen-attr-helper.c
I found that building on OpenWrt/musl failed with:

	sepolgen-ifgen-attr-helper.c:152:16: error: 'PATH_MAX' undeclared ...

Musl is less "generous" than glibc in recursively including header files,
and I suspect this is the reason for this error. Explicitly including
limits.h fixes the problem.

Signed-off-by: W. Michael Petullo <mike@flyn.org>